### ISSUE TITLE
Post.excerpt

### ISSUE THREAD

**Issue by sira313** [zhwangart/hexo-theme-ocean#1]
How do i enable post.excerpt? It looks like all post in home page is viewing full of content...
Thank you
![ss](https://user-images.githubusercontent.com/45110036/49106651-4b886600-f2b6-11e8-9018-34f01417f0c7.png)

**Comment by sira313** [comment]
solved by [this plugin](https://www.npmjs.com/package/hexo-excerpt)
thanks

**Comment by zhwangart** [comment]
> solved by [this plugin](https://www.npmjs.com/package/hexo-excerpt)
> thanks

I wrote this in markdown:
```
title: Markdown
author:
tags:
  - Markdown
date: 
---
Markdown是一种轻量级标记语言，它以纯文本形式(易读、易写、易更改)编写文档，并最终以HTML格式发布。
<!--More-->
```
