### ISSUE TITLE
hexo 我用了你的主题，可是为什么首页都会直接把内容都给展示出来了？你的怎么没有展示？是我哪里调错了么？

### ISSUE THREAD

**Issue by hevze** [zhwangart/hexo-theme-ocean#10]
hexo 我用了你的主题，可是为什么首页都会直接把内容都给展示出来了？你的怎么没有展示？是我哪里调错了么？

**Comment by zhwangart** [comment]
@hevze 这里写了 https://github.com/zhwangart/gitalk/issues/6#issuecomment-449741554
