### ISSUE TITLE
右边导航栏菜单的多语言无法生效？

### ISSUE THREAD

**Issue by fireantzhang** [zhwangart/hexo-theme-ocean#11]
导航栏如果要用多语言的话，该怎么设置，希望提供下示例，谢谢博主。

**Comment by zhwangart** [comment]
> @fireantzhang  导航栏如果要用多语言的话，该怎么设置，希望提供下示例，谢谢博主。

总结了一些常见问题：https://zhwangart.github.io/2019/07/02/Ocean-Issues/
