### ISSUE TITLE
能不能增加tag

### ISSUE THREAD

**Issue by JYlsc** [zhwangart/hexo-theme-ocean#12]

**Comment by JYlsc** [comment]
主题好好看，但是能不能新增tag标签功能呢？

**Comment by nikeman0806** [comment]
i want to add tags, categories in sidebar :)

**Comment by zhwangart** [comment]
@JYlsc @nikeman0806 已经添加了 tags ，在 css 中也加入了对应图标展示样式！

你需要 新建 一个 tags 的 page ，就像新建 相册 一样，然后在 source 中有一个这样的目录：tags/index.md 在 MD 文件 头部 如下标注：
```
title: Tags
type: tags
layout: "tags"
```
