### ISSUE TITLE
请问目录怎么配置？

### ISSUE THREAD

**Issue by leo95123** [zhwangart/hexo-theme-ocean#13]
我的hexo 部分配置如下：
url: http://xxxxx.coding.me/blog
root: /blog/
加载了ocean后ocean的全部资源文件路径全是错的。

**Comment by zhwangart** [comment]
> 我的hexo 部分配置如下：
> url: http://xxxxx.coding.me/blog
> root: /blog/
> 加载了ocean后ocean的全部资源文件路径全是错的。

404 ？

**Comment by leo95123** [comment]
> > 我的hexo 部分配置如下：
> > url: http://xxxxx.coding.me/blog
> > root: /blog/
> > 加载了ocean后ocean的全部资源文件路径全是错的。
> 
> 404 ？

是的，后来解决了，忘记了怎么配置的；但是404.html资源报404，后来我单独把404.html的要引用的资源路径改了一下就解决了。但是我不知道后面是否还会出现这种问题。
