### ISSUE TITLE
除了首页，其他页面搜索功能不能正常使用。

### ISSUE THREAD

**Issue by andus-top** [zhwangart/hexo-theme-ocean#14]
比如我在about页面搜索，点击文章后，浏览器地址为：localhost:4000/about/文章路径

**Comment by zhwangart** [comment]
> @andus-top 

我研究发现 hexo-generator-search 生成的 xml 文件 url 就像精神病一样，所以去请教了这个插件的作者，你可以关注一下：https://github.com/wzpan/hexo-generator-search/issues/53#issue-473830304
我目前比较笨的办法就是 `hexo g` 之后检查下 search.xml 中文章的 url 是否正确，然后再 `hexo d`

**Comment by andus-top** [comment]
> > @andus-top
> 
> 我研究发现 hexo-generator-search 生成的 xml 文件 url 就像精神病一样，所以去请教了这个插件的作者，你可以关注一下：[wzpan/hexo-generator-search#53 (comment)](https://github.com/wzpan/hexo-generator-search/issues/53#issue-473830304)
> 我目前比较笨的办法就是 `hexo g` 之后检查下 search.xml 中文章的 url 是否正确，然后再 `hexo d`

好的，我去尝试一下。感谢

**Comment by andus-top** [comment]
我发现将 node_modules/hexo-generator-searchdb/templates/xml.ejs 文件中的：
`<url><%- encodeURIComponent(config.root + post.path) %></url>` 
修改为
`<url><%- encodeURI(config.root + post.path) %></url>`
就不存在其他页面不能搜索的问题了
