### ISSUE TITLE
希望能够添加百度统计和 google analytics

### ISSUE THREAD

**Issue by FrancisKong** [zhwangart/hexo-theme-ocean#16]
希望能像 [next 主题](https://github.com/iissnan/hexo-theme-next/wiki/%E6%B7%BB%E5%8A%A0-Google---%E7%99%BE%E5%BA%A6-%E7%BB%9F%E8%AE%A1)那样填入统计 ID 后就自动启用网站统计

**Comment by zhwangart** [comment]
> 希望能像 next 主题那样填入统计 ID 后就自动启用网站统计

这个我需要研究一下～
