### ISSUE TITLE
post中插入图片生成的连接错误

### ISSUE THREAD

**Issue by amaothree** [zhwangart/hexo-theme-ocean#17]
首先在配置文件中开启了post_asset_folder
然后在对应的文件夹里放入了文件1.png
再在对应的post里用  {% asset_img 1.png %} 方式插入，结果无论是本地浏览还是推上去都无法显示。
我的网址为amaois.wang
查看生成的静态文件发现路径变成了
```
 <img src="/.wang//02/23/项目环境安装简易指南/1.png">
```
实际上应该是
```
<img src="/2019/02/23/项目环境安装简易指南/1.png">
```
才可以正确显示。
望修复。

**Comment by amaothree** [comment]
关于如何修改hexo编译静态页面时的逻辑，有什么意见吗？我试着修改一下？主要是不知道编译代码在哪里。

**Comment by zhwangart** [comment]
> @amaothree 

十分抱歉！你这个问题我一时还不知道该怎么解决，先等等看有没有高手来解答~

**Comment by skywb** [comment]
之前我也遇到了， 是因为hexo-asset-image插件有个小错误导致的  可以看一下博客最后面的修改方法， 地址 ： https://sonky.top/other/hexo-fix-picture/

**Comment by amaothree** [comment]
> 之前我也遇到了， 是因为hexo-asset-image插件有个小错误导致的 可以看一下博客最后面的修改方法， 地址 ： https://sonky.top/other/hexo-fix-picture/

我解决了这个问题，其实直接卸载hexo-asset-image就好，因为hexo现在已经不需要这个插件就能支持文章资源文件夹了。安装插件反而会导致路径出错。因此请直接卸载插件以防引起冲突。
`npm uninstall --save hexo-asset-image`

hexo官方资源文件夹使用方式👇
https://hexo.io/zh-cn/docs/asset-folders.html

介于问题不再复现，因此现关闭此issue， 若有人复现问题，请再reopen。
