### ISSUE TITLE
is_home()、is_post() 函数判断不正确

### ISSUE THREAD

**Issue by andus-top** [zhwangart/hexo-theme-ocean#18]
在busuanzi.ejs中，写入如下代码：
`is_home:<%- is_home() %>`
```is_post:<%-` is_post() %>```
不管是在主页，还是在文章内容页，结果都为false

**Comment by zhwangart** [comment]
也困扰我很久的问题，但是在其他网友的 hexo 上部署就能正常显示，我也曾在 hexo 上提过 issue https://github.com/hexojs/hexo/issues/3483

**Comment by tootal** [comment]
同样遇到这个问题。

**Comment by andus-top** [comment]
> 也困扰我很久的问题，但是在其他网友的 hexo 上部署就能正常显示，我也曾在 hexo 上提过 issue [hexojs/hexo#3483](https://github.com/hexojs/hexo/issues/3483)

博主之前用hexo 3.8.0 解决过这个问题吗

**Comment by zhwangart** [comment]
> 博主之前用hexo 3.8.0 解决过这个问题吗
现在就是 3.8.0 并不曾解决~

**Comment by andus-top** [comment]
> > 博主之前用hexo 3.8.0 解决过这个问题吗
> 
> 现在就是 3.8.0 并不曾解决~

好吧，我用的hexo3.9.0。那我暂时就全部显示了。看起来也不是很伤大雅，哈哈哈

**Comment by stevenjoezhang** [comment]
建议将`partial`中的`cache`设置为false

**Comment by andus-top** [comment]
> 建议将`partial`中的`cache`设置为`false`

优秀，按照你的方式，果然可以，赞
