### ISSUE TITLE
导航栏图标部分不显示

### ISSUE THREAD

**Issue by andus-top** [zhwangart/hexo-theme-ocean#19]
当我导航栏只要5个时，能正常显示文字前面的图标。
当我导航栏有6个时，第5个，第6个的图标都不显示了。
我的博客地址：https://andus-top.github.io/

**Comment by zhwangart** [comment]
你看下这个是否对你有帮助~
[关于 Ocean 使用中的问题·2-1-相册、分类、标签…菜单对应图标](https://zhwangart.github.io/2019/07/02/Ocean-Issues/#2-1-相册、分类、标签…菜单对应图标)

**Comment by andus-top** [comment]
> 你看下这个是否对你有帮助~
> [关于 Ocean 使用中的问题·2-1-相册、分类、标签…菜单对应图标](https://zhwangart.github.io/2019/07/02/Ocean-Issues/#2-1-%E7%9B%B8%E5%86%8C%E3%80%81%E5%88%86%E7%B1%BB%E3%80%81%E6%A0%87%E7%AD%BE%E2%80%A6%E8%8F%9C%E5%8D%95%E5%AF%B9%E5%BA%94%E5%9B%BE%E6%A0%87)

谢谢博主，我找到原因了。因为我第五图标的缩进不对(notepad++中没看出来)，导致styl的解析不正确。
