### ISSUE TITLE
手机端显示有bug

### ISSUE THREAD

**Issue by qq40171204** [zhwangart/hexo-theme-ocean#2]
在手机上打开网站，视频会显示在上面，请假一下需要怎么设置一下

**Comment by zhwangart** [comment]
我更新了 fancybox ，修正了一下视频在微信中黑幕的问题，但是还是没有做到自动播放！但是在手机浏览器中打开是没有问题的，目前我检查只是微信中不行。
另外新增了视频格式：ogg 与 webm，建议你更新一下主题，会注意到我修改主题 _config.yml 中的：
``` xml
ocean_video_poster: http://source.zhwangart.com/hexo/themes/ocean/video/ocean.png
ocean_video_src: http://source.zhwangart.com/hexo/themes/ocean/video/ocean.mp4
```
改为了：
``` xml
ocean_video_poster: http://source.zhwangart.com/hexo/themes/ocean/video/
ocean_video_src: http://source.zhwangart.com/hexo/themes/ocean/video/
```

**Comment by haocaiMP** [comment]
微信中用这个方法就可以了（测试ok）
document.addEventListener("WeixinJSBridgeReady", function() {
      document.getElementById("videoID").play();
    })
有个前提就是引入 微信的api 
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
