### ISSUE TITLE
markdown渲染的样式可以修改吗

### ISSUE THREAD

**Issue by skywb** [zhwangart/hexo-theme-ocean#25]
默认的自己感觉没有typora中自己导入的主题好看， 想换一下， 找了一下，hexo可以修改渲染引擎，但是那个也不支持修改样式， 然后我想修改一下css样式表， 结果没找到。 请问这个可以更改吗。

**Comment by zhwangart** [comment]
> @skywb 默认的自己感觉没有typora中自己导入的主题好看， 想换一下， 找了一下，hexo可以修改渲染引擎，但是那个也不支持修改样式， 然后我想修改一下css样式表， 结果没找到。 请问这个可以更改吗。

主要的应该是在：`css/_partial/article.styl` 、 `css/_partial/highlight.styl` 和 `css/_partial/_extend.styl`

**Comment by skywb** [comment]
> > @skywb 默认的自己感觉没有typora中自己导入的主题好看， 想换一下， 找了一下，hexo可以修改渲染引擎，但是那个也不支持修改样式， 然后我想修改一下css样式表， 结果没找到。 请问这个可以更改吗。
> 
> 主要的应该是在：`css/_partial/article.styl` 、 `css/_partial/highlight.styl` 和 `css/_extend.styl`

好的， 谢谢
