### ISSUE TITLE
如何添加 Valine 评论插件的支持

### ISSUE THREAD

**Issue by YoungSx** [zhwangart/hexo-theme-ocean#29]
作者能否添加此插件的支持，或者我自己进行添加的话，该怎么做呢~

**Comment by zhwangart** [comment]
> 作者能否添加此插件的支持，或者我自己进行添加的话，该怎么做呢~

我来加一个～

**Comment by zhwangart** [comment]
> 作者能否添加此插件的支持，或者我自己进行添加的话，该怎么做呢~

已经添加 Valine ， git pull
