### ISSUE TITLE
换上 Ocean 并开启 Valine 后，我原本的 Valine 评论空了

### ISSUE THREAD

**Issue by YoungSx** [zhwangart/hexo-theme-ocean#30]
原主题：
https://github.com/Ben02/hexo-theme-Anatole

现在换上 Ocean 主题，并开启 Valine，我原本 Theme 页面对应的 Valine 评论空掉了。

两边 leancloud 用的是同一套，并且我在两个 Theme 之间切换了好几次来试验，原主题没问题，Ocean 下是空的。

**Comment by zhwangart** [comment]
> 原主题：
> https://github.com/Ben02/hexo-theme-Anatole
> 
> 现在换上 Ocean 主题，并开启 Valine，我原本 Theme 页面对应的 Valine 评论空掉了。
> 
> 两边 leancloud 用的是同一套，并且我在两个 Theme 之间切换了好几次来试验，原主题没问题，Ocean 下是空的。

尝试加上你原有的这个值呢？
`path: window.location.pathname,`

**Comment by YoungSx** [comment]
大体对比了一下两个主题下的 Comment 请求的 Query String Parameters 部分：

原主题 Anatole:
`
where: {"url":"/2018/01/21/%E9%97%B2%E6%89%AF%E4%B8%80%E4%B8%8B%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%AE%9E%E4%B9%A0%E7%9A%84%E6%97%A5%E5%AD%90/"}
limit: 1000
order: -createdAt
`

Ocean:
`
where: {"$or":[{"rid":{"$exists":false}},{"rid":""}],"url":"/2018/01/21/闲扯一下哔哩哔哩实习的日子/"}
order: -createdAt,-insertedAt
limit: 0
count: 1
`

**Comment by YoungSx** [comment]
@zhwangart 
我用 CURL 做了以下尝试，把 Ocean 的 Comment 请求做了以下修改就能获取到我原本的数据了：

limit=0 => limit=1000

url: "/2018/01/21/闲扯一下哔哩哔哩实习的日子/" => url: "url":"/2018/01/21/%E9%97%B2%E6%89%AF%E4%B8%80%E4%B8%8B%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%AE%9E%E4%B9%A0%E7%9A%84%E6%97%A5%E5%AD%90/"

limit 我不太清楚是什么情况，不过可以看出我用的原主题是把 path 进行了 url encode 之后当作 url 的参数，而 Ocean 是直接把 path 当作 url 参数的。

**Comment by YoungSx** [comment]
@zhwangart 
对比了一下两个主题的源代码，发现是 Valine 的版本问题。
我的原主题使用的是 1.1.7，而 Ocean 使用的是最新版。
这应该是 Valine 的锅，新旧版本不兼容，数据不互通，我去看看有没有什么迁移数据的方法了。
