### ISSUE TITLE
主页文章如何合起来使用阅读全文

### ISSUE THREAD

**Issue by arukione** [zhwangart/hexo-theme-ocean#32]
我克隆大佬的主题后，发现大佬的博客那边是会把文章给合起来并显示阅读全文按钮的，但是我这边不会这样显示，会直接展现整篇文章，如何才能在这个主题中使用这个功能

**Comment by zhwangart** [comment]
> 我克隆大佬的主题后，发现大佬的博客那边是会把文章给合起来并显示阅读全文按钮的，但是我这边不会这样显示，会直接展现整篇文章，如何才能在这个主题中使用这个功能

显示文章摘要：[传送门](https://zhwangart.github.io/2019/07/02/Ocean-Issues/#1-1-如何首页默认显示摘要？)
