### ISSUE TITLE
无法显示阅读更多.../Read More...

### ISSUE THREAD

**Issue by ZhangKingsasa** [zhwangart/hexo-theme-ocean#38]
在主页中，会把每篇文章完全的展示出来。
不是我操作的问题，我重置了hexo项目，ocean主题重新拉的，什么都是新的，但是还是有问题。
是不是我什么插件没安装？

**Comment by zhwangart** [comment]
> 在主页中，会把每篇文章完全的展示出来。
> 不是我操作的问题，我重置了hexo项目，ocean主题重新拉的，什么都是新的，但是还是有问题。
> 是不是我什么插件没安装？

[如何首页默认显示摘要？](https://zhwangart.github.io/2019/07/02/Ocean-Issues/#1-1-如何首页默认显示摘要？)

**Comment by ZhangKingsasa** [comment]
对不起，我是智障...
