### ISSUE TITLE
感谢制作，根据个人喜好小小修改了一下，可以嘛

### ISSUE THREAD

**Issue by galikeoy** [zhwangart/hexo-theme-ocean#4]
https://keoy.xyz/ 大家快来玩啊(°∀°)ﾉ

**Comment by zhwangart** [comment]
> @galikeoy 
> https://keoy.xyz/ 大家快来玩啊(°∀°)ﾉ

非常可以的~

**Comment by galikeoy** [comment]
> > @galikeoy
> > https://keoy.xyz/ 大家快来玩啊(°∀°)ﾉ
> 
> 非常可以的~

好的~
