### ISSUE TITLE
如何将一部分文章在首页隐藏

### ISSUE THREAD

**Issue by yxy-biubiubiu** [zhwangart/hexo-theme-ocean#40]
非常喜欢这个主题，但是有网上提供的一些方案无法解决这个问题，有些文章不想出现在首页，不知道有没有办法来解决呢

**Comment by zhwangart** [comment]
> 非常喜欢这个主题，但是有网上提供的一些方案无法解决这个问题，有些文章不想出现在首页，不知道有没有办法来解决呢

目前没有设计这个功能呀～

**Comment by stevenjoezhang** [comment]
可以使用插件： https://github.com/next-theme/hexo-generator-indexed
