### ISSUE TITLE
相册加的图片怎么没有用

### ISSUE THREAD

**Issue by conan51551** [zhwangart/hexo-theme-ocean#53]
在gallery里面添加的图片没有用

**Comment by conan51551** [comment]
---
title: Gallery
date: 2021-12-03 18:23:29
albums: [
        ["https://z3.ax1x.com/2021/11/27/oeWnHO.md.jpg","描述"],
        ]
---
我是这样跟着文档加的图片

**Comment by conan51551** [comment]
albums:
  [
    ["点击放大后的url", "图片展示的url", "图片描述"],
  ]
已经可以了，解决方法是发现这个有三个参数

**Comment by real-jiakai** [comment]
["点击放大后的url", "图片展示的url", "图片描述"],
前面两个url填一样就OK了
