### ISSUE TITLE
关于【收藏】页面

### ISSUE THREAD

**Issue by snorlaxse** [zhwangart/hexo-theme-ocean#58]
此页面是如何添加的呢  ↓↓↓
![image](https://user-images.githubusercontent.com/19644938/163702201-39e8939c-172c-422c-bb8c-5ff6f63712e2.png)

**Comment by zhwangart** [comment]
@snorlaxse 这里有一个同样问题的答案：https://github.com/zhwangart/gitalk/issues/7#issuecomment-906849126
