### ISSUE TITLE
关于hexo-inverted.svg以及hexo.svg

### ISSUE THREAD

**Issue by real-jiakai** [zhwangart/hexo-theme-ocean#59]
大哥，想问一下，博客中的hexo.inverted.svg以及hexo.svg这两个logo是去哪个网站上设计才符合主题的？我去png转svg的网站，转出来的图片不符合样式。

**Comment by zhwangart** [comment]
> 大哥，想问一下，博客中的hexo.inverted.svg以及hexo.svg这两个logo是去哪个网站上设计才符合主题的？我去png转svg的网站，转出来的图片不符合样式。

1. png 是无法转 svg 的
2. 通常 logo 都是由设计师设计出稿件，然后提供 svg 格式来使用，当然不涉及到商用可以到一个图标网站下载一些自己喜欢的使用，例如：iconfont 上边搜一个～

**Comment by real-jiakai** [comment]
好的，感谢指点。
