### ISSUE TITLE
推荐支持流程图，插件：hexo-filter-mermaid-diagrams

### ISSUE THREAD

**Issue by ShijayHuo** [zhwangart/hexo-theme-ocean#64]
在文章中展示流程图，如下：
<img width="691" alt="image" src="https://user-images.githubusercontent.com/36189354/217699242-e9c1cd39-9bf5-4612-a4cc-772847777375.png">

使用方式，文章内编写文本，如下：
```  
    ```mermaid
        flowchart LR
        A[Start] --> B{Is it?}
        B -->|Yes| C[OK]
        C --> D[Rethink]
        D --> B
        B ---->|No| E[End]
     ```
```
个人写了个文档：https://aaaaaajie.github.io/2023/02/08/mermaid/

**Comment by zhwangart** [comment]
> 在文章中展示流程图，如下： <img alt="image" width="691" src="https://user-images.githubusercontent.com/36189354/217699242-e9c1cd39-9bf5-4612-a4cc-772847777375.png">
> 
> 使用方式，文章内编写文本，如下：
> 
> ```
>     ```mermaid
>         flowchart LR
>         A[Start] --> B{Is it?}
>         B -->|Yes| C[OK]
>         C --> D[Rethink]
>         D --> B
>         B ---->|No| E[End]
>      ```
> ```
> 
> 个人写了个文档：https://aaaaaajie.github.io/2023/02/08/mermaid/

GitHub 不支持密码后，我无法提交代码了。
