### ISSUE TITLE
请问，相册的img-url应该怎么写，被引用的img应该放在哪个路径下呢

### ISSUE THREAD

**Issue by Ilak-0** [zhwangart/hexo-theme-ocean#66]

**Comment by zhwangart** [comment]
没有规定必须要放在什么路径，能被访问到即可，可以放在 images 下，或者上传到一个图床上，我目前使用的是 [路过图床](https://imgse.com)

**Comment by Ilak-0** [comment]
好的，因为我是用相对路径总是没成功，就挺奇怪的，谢谢
