### ISSUE TITLE
为什么设置中文不生效

### ISSUE THREAD

**Issue by fantasyhh** [zhwangart/hexo-theme-ocean#7]
site 中已经设置了 language: zh-CN
还有
//       &:nth-child(3)         // gallery
//          .nav-item-link
//           &::before
//            content '\f1a9'
//        &:nth-child(4)         // about
//          .nav-item-link
//            &::before
//              content '\f174'
已取消about跟gallery 但是还是有

**Comment by fantasyhh** [comment]
我说的是导航栏不是中文

**Comment by zhwangart** [comment]
> 我说的是导航栏不是中文

在 hexo config 中设置
