### ISSUE TITLE
关于归档页面问题

### ISSUE THREAD

**Issue by AngelVivian** [zhwangart/hexo-theme-ocean#8]
归档页面需要自己写还是默认会生成？可否说明一下

**Comment by zhwangart** [comment]
> @AngelVivian 
> 归档页面需要自己写还是默认会生成？可否说明一下

默认会有的

**Comment by AngelVivian** [comment]
好的，谢谢你啦！


 
---原始邮件---
发件人: "zhwangart"<notifications@github.com>
发送时间: 2019年4月27日(星期六) 晚上10:14
收件人: "zhwangart/hexo-theme-ocean"<hexo-theme-ocean@noreply.github.com>;
抄送: "AngelVivian"<1552412931@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [zhwangart/hexo-theme-ocean] 关于归档页面问题 (#8)


 
@AngelVivian
 归档页面需要自己写还是默认会生成？可否说明一下
  
默认会有的
